### ISSUE TITLE
Export rejection info

### ISSUE THREAD

**Issue by estellerv** [annesodub/ABRBABY#9]
Hi @annesodub ! Could you please help me exporting the rejection information from the last sanity check script (https://github.com/annesodub/ABRBABY/blob/main/abrbaby_process_ERP_sanity_exportdata.m) ?
Ideally I'd like to get one tab per participant containing all the epochs (epoch number and latency) and a value indicating if the epoch has been rejected or kept. It will allow me to know whether the visually "bad" epochs were rejected or not. Thanks!

**Comment by annesodub** [comment]
Hi,

Yes, the format that I suggested allow to keep track of all events with a status (0 rejected ; 1 not rejected). You should produce a .csv file with the following columns (with a header) : 

- Triall#        
- Condition        
- Latency (ms)            
- Rejected 

Do you see any information missing?

**Comment by estellerv** [comment]
Hi,
Yes this format seems to fit prefectly with what I need. I don't see any information missing.

However I've been thinking of adding a rejection threshold based on these information. It want determine which subject to remove from analysis depending on the rejection rate per participant. Also, it would be great to have the same .csv file for the FFR data (without the 'condition' column because there is only one condition) and include the rejection rates from FFR data in the decision for participant rejection.
How would you do that ? (tell me if I'm not clear)

Thank you!

**Comment by annesodub** [comment]
Hi, what about including the detection thresholds (rej_low, rej_high) in the filename? 

As for the FFR data, please open a separate issue and point to the function that needs to be modified (you can also refer to this issue)

Now, in order to generate this file I recommend that you : 

Around line 138, add the following line :
`[EEG_all,idx_rejected_all] =  pop_eegthresh(EEG,1,elec ,rej_low, rej_high, win_of_interest(1), win_of_interest(2),0,1);`
in order to get indices of the trials which were rejected (without messing around with the relative indices)

Then  
`trial_index = 1:EEG.trials;`
`condition = {EEG.event.type} ; `
`latency = [EEG.event.latency] ;`
`rejected = ismember(trial_index,idx_rejected_all) ; `
WARNING :  Please make sure that the variables names (trial_index, condition, latency, rejected) do NOT already exist in the code (I did not test).

Then create a table : 
list_trial_infos = table(trial_index',condition',latency',rejected') ; 

Then save this table into a csv file (use function writetable) :
`writetable(list_trial_info,fullfile(INDIR,subjects{jj},strcat(filename,'_infos_trials.csv'))) ; `

Let me know if you experience any difficulty.

**Comment by estellerv** [comment]
Done, see PR #19
